apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: ctsebackend02
  name: ctsebackend02
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ctsebackend02
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ctsebackend02
    spec:
      containers:
        # - image: it19062266/ctse_user:latest
        - image: it19062266/ctse_user:{{tag}}
          imagePullPolicy: Always
          name: ctse_user
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - containerPort: 5001
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30