apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ctsebackend02
  name: ctsebackend02
spec:
  ports:
    - port: 5001
      protocol: TCP
      targetPort: 5001
  selector:
    app: ctsebackend02
status:
  loadBalancer: {}